trigger:
- build

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: mv config_example.js config.js

- script: sed -i "s|../_/|https://$APIHOSTNAME/_/|" config.js

- script: sed -i "s|Directus Demo|Rise Community Art|" config.js

- task: CopyFiles@2
  inputs:
    Contents: |
     **
     !.git/**/*
     !azure-pipelines.yml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'